export enum CompanyRole {
  COMPANY_OWNER = 'COMPANY_OWNER',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  COMPANY_SALES = 'COMPANY_SALES',
  COMPANY_SUPPORT = 'COMPANY_SUPPORT',
  COMPANY_READONLY = 'COMPANY_READONLY',
}

export enum MembershipStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INVITED = 'INVITED',
}
